### ISSUE TITLE
Intermittent Problem with Random Numbers

### ISSUE THREAD

**Issue by bbusschots-nuim** [bbusschots/hsxkpasswd#14]
This doesn't happen often, but every now and then it does:

`ERROR - Crypt::HSXKPasswd::password(): Failed to generate password with the following error: ERROR - Crypt::HSXKPasswd::_increment_random_cache(): random function returned and invalid value (6.1053317040205e-05) at /usr/local/bin/hsxkpasswd line 464.
 at /usr/local/bin/hsxkpasswd line 464.`

**Comment by bbusschots** [comment]
Resolved by commit https://github.com/bbusschots/hsxkpasswd/commit/aac07ee5b59a13be48f72e8988a49d969df0cb7c

**Comment by lukeallister** [comment]
I am still getting this bug.  I ran it from both the cpan Crypt and installing from source.  Still get the "invalid value" with small numbers.
